### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by JustBlackBird** [komakino/roman-numerals#1]
As I can see there is no license info in `composer.json`. So the question is what's the license the library is published under?

**Comment by komakino** [comment]
Oh, sorry. I'll update later today when I get home. Guess it's MIT.

Den tors 15 sep. 2016 15:48Dmitriy Simushev notifications@github.com
skrev:

**Comment by komakino** [comment]
License (MIT) and author information added to composer.json. New tag v1.0.2.

**Comment by JustBlackBird** [comment]
Thank you!
